apiVersion: v1
kind: Secret
metadata:
  name: mobility-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: connected-car
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secrets.mongoRootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.mongoRootPassword | quote }}
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  VWORLD_API_KEY: {{ .Values.secrets.vworldApiKey | quote }}