sonar.projectKey=k8s-mini-mongo-consumer
sonar.projectName=k8s-mini-mongo-consumer
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py
sonar.python.version=3.11
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/tests/**