sonar.projectKey=k8s-mini-redis-consumer
sonar.projectName=k8s-mini-redis-consumer
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py
sonar.python.version=3.12
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/tests/**