imagePullSecrets:
  - name: harbor-secret

command:
  api:
    replicaCount: 2
    image: "10.0.2.111:80/k8s-mini/telemetry-ingest-api:v1"
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      cpuUtilization: 50
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  consumer:
    replicaCount: 2
    image: "10.0.2.111:80/k8s-mini/telemetry-mongo-consumer:v1"
    hpa:
      requests:
        cpu: "150m"
        memory: "128Mi"
      limits:
        cpu: "600m"
        memory: "256Mi"

secrets:
  mongoRootUsername: "admin"
  mongoRootPassword: ""
  mongoUri: ""
  redisPassword: ""
  vworldApiKey: ""
