apiVersion: v1
kind: ConfigMap
metadata:
  name: mobility-config
  namespace: miniproject
  labels:
    app: connected-car
data:
  # --- Kafka ---
  KAFKA_BROKERS: "kafka-svc:9092"
  KAFKA_BOOTSTRAP: "kafka-svc:9092"
  KAFKA_TOPIC: "car.telemetry.events"
  KAFKA_GROUP_ID: "vehicle-projector"

  # --- MongoDB ---
  MONGO_URI: "mongodb://mongo-svc:27017/car_db"
  MONGO_DB: "car_db"
  MONGO_COLLECTION: "telemetry_history"

  # --- Redis ---
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  REDIS_TTL_SEC: "60"

  # --- API Ports ---
  QUERY_API_PORT: "8000"
  QUERY_API_HOST: "0.0.0.0"

  # --- Dummy Data Server ---
  INGEST_SERVER_URL: "http://connected-car-command-svc/api/query/telemetry"
