apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: command-api-hpa
  namespace: miniproject
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: connected-car-command
  minReplicas: 2      # 평소에 유지할 최소 파드 수
  maxReplicas: 10     # 트래픽 폭주 시 늘릴 최대 파드 수
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # CPU 사용률이 50%를 넘으면 스케일 아웃
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: query-api-hpa
  namespace: miniproject
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: connected-car-query
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
