apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-nfs-0
  labels:
    app: mongo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 10.0.2.100
    path: /srv/nfs/mongo

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-nfs-0
  labels:
    app: redis
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 10.0.2.100
    path: /srv/nfs/redis

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-nfs-0
  labels:
    app: kafka
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 10.0.2.100
    path: /srv/nfs/kafka
