apiVersion: v1
kind: Secret
metadata:
  name: mobility-secret
  namespace: miniproject
  labels:
    app: connected-car
type: Opaque
stringData:
  # MongoDB 인증 정보
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "mongo1234"
  MONGO_URI: "mongodb://admin:mongo1234@mongo-svc:27017/?authSource=admin"

  # Redis 비밀번호
  REDIS_PASSWORD: "redis1234"

  # VWorld 지도 API 키
  VWORLD_API_KEY: "323FDD38-6DFC-319E-94AF-EAC78876A2A6"
